<?php

use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$faker = Faker\Factory::create();
    	DB::table('products')->insert(
    		[
    		[
    		'pname' => 'Iphone 5s',
    		'preview' => 'Iphone 5s Preview',
    		'detail'=> 'Iphone 5s Detail',
    		'spec'=>'Iphone 5s Spec',
    		'image'=>'product/smartphone/iphone5s.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'5000000',
    		'cat_id'=>'1',
    		'brand_id'=>'1',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'apple,iphone,smartphone,iphone5s',
    		],
    		[
    		'pname' => 'Iphone 6 Plus',
    		'preview' => 'Iphone 6 Plus Preview',
    		'detail'=> 'Iphone 6 Plus Detail',
    		'spec'=>'Iphone 6 Plus Spec',
    		'image'=>'product/smartphone/iphone6plus.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'15000000',
    		'cat_id'=>'1',
    		'brand_id'=>'1',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'apple,iphone,smartphone,iphone6plus',
    		],
    		[
    		'pname' => 'LG G4',
    		'preview' => 'LG G4 Preview',
    		'detail'=> 'LG G4 Detail',
    		'spec'=>'LG G4 Spec',
    		'image'=>'product/smartphone/lgg4.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'12000000',
    		'cat_id'=>'1',
    		'brand_id'=>'3',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'lg,g4,smartphone',
    		],
    		[
    		'pname' => 'Samsung Galaxy S6',
    		'preview' => 'Samsung Galaxy S6 Preview',
    		'detail'=> 'Samsung Galaxy S6 Detail',
    		'spec'=>'Samsung Galaxy S6 Spec',
    		'image'=>'product/smartphone/galaxys6.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'16000000',
    		'cat_id'=>'1',
    		'brand_id'=>'2',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'samsung,galaxy,smartphone,galaxys6',
    		],
    		[
    		'pname' => 'Xiaomi Redmi Note 4',
    		'preview' => 'Xiaomi Redmi Note 4 Preview',
    		'detail'=> 'Xiaomi Redmi Note 4 Detail',
    		'spec'=>'Xiaomi Redmi Note 4 Spec',
    		'image'=>'product/smartphone/xiaoredminote4.jpg',
    		'rating'=>3,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'5600000',
    		'cat_id'=>'1',
    		'brand_id'=>'6',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'xiaomi,redminote4,smartphone,china',
    		],
    		[
    		'pname' => 'Nokia Lumia 720',
    		'preview' => 'Nokia Lumia 720 Preview',
    		'detail'=> 'Nokia Lumia 720 Detail',
    		'spec'=>'Nokia Lumia 720 Spec',
    		'image'=>'product/smartphone/lumnia720.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'9500000',
    		'cat_id'=>'1',
    		'brand_id'=>'4',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'nokia,lumia,smartphone,lumia720',
    		],
    		[
    		'pname' => 'Motorola Droid Turbo',
    		'preview' => 'Motorola Droid Turbo Preview',
    		'detail'=> 'Motorola Droid Turbo Detail',
    		'spec'=>'Motorola Droid Turbo Spec',
    		'image'=>'product/smartphone/droidturbo.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'10250000',
    		'cat_id'=>'1',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'motorola,droid,smartphone,droidturbo,other',
    		],
    		[
    		'pname' => 'Asus Zenphone 5',
    		'preview' => 'Asus Zenphone 5 Preview',
    		'detail'=> 'Asus Zenphone 5 Detail',
    		'spec'=>'Asus Zenphone 5 Spec',
    		'image'=>'product/smartphone/zenphone5.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'6500000',
    		'cat_id'=>'1',
    		'brand_id'=>'5',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'asus,zenphone,smartphone,zenphone5',
    		],
    		[
    		'pname' => 'LG Prada 3.0',
    		'preview' => 'LG Prada 3.0 Preview',
    		'detail'=> 'LG Prada 3.0 Detail',
    		'spec'=>'LG Prada 3.0 Spec',
    		'image'=>'product/smartphone/prada3.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'6000000',
    		'cat_id'=>'1',
    		'brand_id'=>'3',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'lg,prada,smartphone,prada3',
    		],
    		[
    		'pname' => 'OPPO R7 Plus',
    		'preview' => 'OPPO R7 Plus Preview',
    		'detail'=> 'OPPO R7 Plus Detail',
    		'spec'=>'OPPO R7 Plus Spec',
    		'image'=>'product/smartphone/oppor7plus.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'12000000',
    		'cat_id'=>'1',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'oppo,china,smartphone,r7plus',
    		],
    		[
    		'pname' => 'Ipad Mini 3',
    		'preview' => 'Ipad Mini 3 Preview',
    		'detail'=> 'Ipad Mini 3 Detail',
    		'spec'=>'Ipad Mini 3 Spec',
    		'image'=>'product/tablet/ipadmini3.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'10000000',
    		'cat_id'=>'2',
    		'brand_id'=>'1',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'apple,ipad,tablet,ipadmini3',
    		],
    		[
    		'pname' => 'iPad Pro 12.9',
    		'preview' => 'Ipad Pro Preview',
    		'detail'=> 'Ipad pro Detail',
    		'spec'=>'Ipad Pro Spec',
    		'image'=>'product/tablet/ipadpro129.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'18000000',
    		'cat_id'=>'2',
    		'brand_id'=>'1',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'apple,ipad,tablet,ipadpro',
    		],
    		[
    		'pname' => 'Lenovo Tab 3',
    		'preview' => 'Lenovo Tab 3 Preview',
    		'detail'=> 'Lenovo Tab 3 Detail',
    		'spec'=>'Lenovo Tab 3 Spec',
    		'image'=>'product/tablet/lenovotab3.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'2700000',
    		'cat_id'=>'2',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'lenovo,tablet,china,lenovotab3',
    		],
    		[
    		'pname' => 'Samsung Tab A',
    		'preview' => 'Samsung Tab A Preview',
    		'detail'=> 'Samsung Tab A Detail',
    		'spec'=>'Samsung Tab A Spec',
    		'image'=>'product/tablet/samsungtaba.jpg',
    		'rating'=>4,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'7490000',
    		'cat_id'=>'2',
    		'brand_id'=>'2',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'samsung,tablet,samsungtaba',
    		],
    		[
    		'pname' => 'Mi Pad 2',
    		'preview' => 'Mi Pad 2 Preview',
    		'detail'=> 'Mi Pad 2 Detail',
    		'spec'=>'Mi Pad 2 Spec',
    		'image'=>'product/tablet/mipad2.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'5500000',
    		'cat_id'=>'2',
    		'brand_id'=>'6',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'xiaomi,mipad,tablet,mipad2,china',
    		],
    		[
    		'pname' => 'Google Nexus 10',
    		'preview' => 'Google Nexus 10 Preview',
    		'detail'=> 'Google Nexus 10 Detail',
    		'spec'=>'Google Nexus 10 Spec',
    		'image'=>'product/tablet/googlenexus10.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'9500000',
    		'cat_id'=>'2',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'google,nexus,tablet,nexus10',
    		],
    		[
    		'pname' => 'Apple Watch Series 2',
    		'preview' => 'Apple Watch Series 2 Preview',
    		'detail'=> 'Apple Watch Series 2 Detail',
    		'spec'=>'Apple Watch Series 2 Spec',
    		'image'=>'product/smart-watch/applewatchseries2.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'11990000',
    		'cat_id'=>'3',
    		'brand_id'=>'1',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'apple,watch,smartwatch,applesmartwatch2',
    		],
    		[
    		'pname' => 'Apple Watch Series 1',
    		'preview' => 'Apple Watch Series 1 Preview',
    		'detail'=> 'Apple Watch Series 1 Detail',
    		'spec'=>'Apple Watch Series 1 Spec',
    		'image'=>'product/smart-watch/applewatchseries1.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'7990000',
    		'cat_id'=>'3',
    		'brand_id'=>'1',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'apple,watch,smartwatch,applesmartwatch1',
    		],
    		[
    		'pname' => 'Motorola Moto 360',
    		'preview' => 'Moto 360 Preview',
    		'detail'=> 'Moto 360 Detail',
    		'spec'=>'Moto 360 Spec',
    		'image'=>'product/smart-watch/moto360.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'6990000',
    		'cat_id'=>'3',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'motorola,watch,smartwatch,moto360',
    		],
    		[
    		'pname' => 'Xiaomi Mi Band 2',
    		'preview' => 'Xiaomi Mi Band 2 Preview',
    		'detail'=> 'Xiaomi Mi Band 2 Detail',
    		'spec'=>'Xiaomi Mi Band 2 Spec',
    		'image'=>'product/smart-watch/miband2.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'990000',
    		'cat_id'=>'3',
    		'brand_id'=>'6',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'xiaomi,watch,smartwatch,miband2,china',
    		],
    		[
    		'pname' => 'Samsung Gear S3',
    		'preview' => 'Samsung Gear S3 Preview',
    		'detail'=> 'Samsung Gear S3 Detail',
    		'spec'=>'Samsung Gear S3 Spec',
    		'image'=>'product/smart-watch/gears3.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'1290000',
    		'cat_id'=>'3',
    		'brand_id'=>'2',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'samsung,watch,smartwatch,gears3,samsunggear',
    		],
    		[
    		'pname' => 'Samsung Gear S2',
    		'preview' => 'Samsung Gear S2 Preview',
    		'detail'=> 'Samsung Gear S2 Detail',
    		'spec'=>'Samsung Gear S2 Spec',
    		'image'=>'product/smart-watch/gears2.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'890000',
    		'cat_id'=>'3',
    		'brand_id'=>'2',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'samsung,watch,smartwatch,gears2,samsunggear',
    		],
    		[
    		'pname' => 'Xiaomi Pistons',
    		'preview' => 'Xiaomi Pistons Preview',
    		'detail'=> 'Xiaomi Pistons Detail',
    		'spec'=>'Xiaomi Pistons Spec',
    		'image'=>'product/accessories/xiaomipistons.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'80000',
    		'cat_id'=>'5',
    		'brand_id'=>'6',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'xiaomi,earphone,pistons,china',
    		],
    		[
    		'pname' => 'Sennheiser HD 4.30i',
    		'preview' => 'Sennheiser HD 4.30i Preview',
    		'detail'=> 'Sennheiser HD 4.30i Detail',
    		'spec'=>'Sennheiser HD 4.30i Spec',
    		'image'=>'product/accessories/senheiserhd4.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'2790000',
    		'cat_id'=>'5',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'senheiser,headphone,hd4,china',
    		],
    		[
    		'pname' => 'Sony Bluetooth MDR-1RBTMK2',
    		'preview' => 'Sony Bluetooth MDR-1RBTMK2 Preview',
    		'detail'=> 'Sony Bluetooth MDR-1RBTMK2 Detail',
    		'spec'=>'Sony Bluetooth MDR-1RBTMK2 Spec',
    		'image'=>'product/accessories/sonymdr1RBTMK2.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'7990000',
    		'cat_id'=>'5',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'sony,headphone,mdr,bluetooth,china',
    		],
    		[
    		'pname' => 'Bluetooth Plantronics Marque 2 M165',
    		'preview' => 'Bluetooth Plantronics Marque 2 M165 Preview',
    		'detail'=> 'Bluetooth Plantronics Marque 2 M165 Detail',
    		'spec'=>'Bluetooth Plantronics Marque 2 M165 Spec',
    		'image'=>'product/accessories/plantronicmarque2.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'7990000',
    		'cat_id'=>'5',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'headphone,plantronics,bluetooth,plantronicmarque2',
    		],
    		[
    		'pname' => 'Romoss SENSE 6 20.000 mAh',
    		'preview' => 'Romoss SENSE 6 Preview',
    		'detail'=> 'Romoss SENSE 6 Detail',
    		'spec'=>'Romoss SENSE 6 M165 Spec',
    		'image'=>'product/accessories/romosssense6.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'289000',
    		'cat_id'=>'5',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'romosssense6,battery,portable,plantronics,romoss',
    		],
    		[
    		'pname' => 'Xiaomi QC 3.0 20.000mAh',
    		'preview' => 'Xiaomi QC 3.0 Preview',
    		'detail'=> 'Xiaomi QC 3.0 Detail',
    		'spec'=>'Xiaomi QC 3.0 M165 Spec',
    		'image'=>'product/accessories/xiaomiqc3.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'929000',
    		'cat_id'=>'5',
    		'brand_id'=>'6',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'xiaomi,china,battery,portable,xiaomiqc3',
    		],
    		[
    		'pname' => 'Xiaomi NDY-02-AN 10.000mAh',
    		'preview' => 'Xiaomi NDY-02-AN Preview',
    		'detail'=> 'Xiaomi NDY-02-AN Detail',
    		'spec'=>'Xiaomi NDY-02-AN M165 Spec',
    		'image'=>'product/accessories/xiaomindy02an.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'399000',
    		'cat_id'=>'5',
    		'brand_id'=>'6',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'xiaomi,china,battery,portable,xiaomindy02an',
    		],
    		[
    		'pname' => 'Galaxy S6 Edge Plus Spigen Phone Case',
    		'preview' => 'Galaxy S6 Edge Plus Spigen Preview',
    		'detail'=> 'Galaxy S6 Edge Plus Spigen Detail',
    		'spec'=>'Galaxy S6 Edge Plus Spigen Spec',
    		'image'=>'product/accessories/samsungs6edgespigen.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'229000',
    		'cat_id'=>'5',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'phonecase,silicon,samsungs6edge',
    		],
    		[
    		'pname' => 'iPhone 7 Plus Case RANVOO 3 in 1',
    		'preview' => 'iPhone 7 Plus Case RANVOO 3 in 1 Preview',
    		'detail'=> 'iPhone 7 Plus Case RANVOO 3 in 1 Detail',
    		'spec'=>'iPhone 7 Plus Case RANVOO 3 in 1 Spec',
    		'image'=>'product/accessories/iphone7pluscaseranvoo.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'329000',
    		'cat_id'=>'5',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'phonecase,silicon,iphone7,ranvoo,apple',
    		],
    		[
    		'pname' => 'Xiaomi Redmi Note 3 Phone Case',
    		'preview' => 'Xiaomi Redmi Note 3 Phone Case Preview',
    		'detail'=> 'Xiaomi Redmi Note 3 Phone Case Detail',
    		'spec'=>'Xiaomi Redmi Note 3 Phone Case Spec',
    		'image'=>'product/accessories/xiaomiredminote3case.jpg',
    		'rating'=>5,
    		'view'=>$faker->numberBetween(0,1000),
    		'price'=>'129000',
    		'cat_id'=>'5',
    		'brand_id'=>'7',
    		'discount'=>$faker->numberBetween(0,4)*10,
    		'tags'=>'phonecase,silicon,xiaomi'
    		]
    		]
    		);
}
}
